services:
  kafka_controller:
    image: apache/kafka:4.3.1
    container_name: kafka_controller
    restart: on-failure
    ports:
      - 5090:5090
    environment:
      - KAFKA_NODE_ID=1 #Identificador
      - KAFKA_PROCESS_ROLES=controller #Regra de atuação

      #Em quais portas esse servidor kafka vai estar 'escutando' conexões
      - KAFKA_LISTENERS=CONTROLLER://:5090
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka_controller:5090
  kafka_broker_1:
    image: apache/kafka:4.3.1
    container_name: kafka_broker_1
    restart: on-failure
    ports:
      - 5091:5091
    environment:
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=broker
      - KAFKA_LISTENERS=INTERNAL://:5091
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka_broker_1:5091, CONTROLLER://kafka_controller:5090
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT, CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka_controller:5090
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    depends_on:
      - kafka_controller
  kafka_broker_2:
    image: apache/kafka:4.3.1
    container_name: kafka_broker_2
    restart: on-failure
    ports:
      - 5092:5092
    environment:
      - KAFKA_NODE_ID=3
      - KAFKA_PROCESS_ROLES=broker
      - KAFKA_LISTENERS=INTERNAL://:5092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka_broker_2:5092, CONTROLLER://kafka_controller:5090
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT, CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka_controller:5090
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    depends_on:
      - kafka_controller
  
  kafka_broker_3:
    image: apache/kafka:4.3.1
    container_name: kafka_broker_3
    restart: on-failure
    ports:
      - 5093:5093
    environment:
      - KAFKA_NODE_ID=4
      - KAFKA_PROCESS_ROLES=broker
      - KAFKA_LISTENERS=INTERNAL://:5093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka_broker_3:5093, CONTROLLER://kafka_controller:5090
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT, CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka_controller:5090
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
  kafka_admin_client:
    container_name: kafka_admin_client
    build:
      context: ..
      dockerfile: docker/Dockerfile.kafka_admin_client
    ports:
      - 5100:5100
    depends_on:
      - kafka_broker_1
      - kafka_broker_2
      - kafka_broker_3
  
  apache-spark-master:
    image: apache/spark:4.0.3
    container_name: apache-spark-master
    restart: on-failure
    ports:
      - 7077:7077
      - 8090:8080
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master #Initialize the master, boosted java knows spark path
    depends_on:
      - kafka_admin_client
  
  apache-spark-worker-1:
    image: apache/spark:4.0.3
    container_name: apache-spark-worker-1
    restart: on-failure
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://apache-spark-master:7077
    environment:
      - SPARK_WORKER_MEMORY=3g
      - SPARK_WORKER_CORES=2
    depends_on:
      - apache-spark-master
    volumes:
      - ../credential/projeto_data_credential.json:/opt/spark/work-dir/projeto_data_credential.json:ro
  apache-spark-worker-2:
    image: apache/spark:4.0.3
    container_name: apache-spark-worker-2
    restart: on-failure
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://apache-spark-master:7077
    environment:
      - SPARK_WORKER_MEMORY=3g
      - SPARK_WORKER_CORES=2
    depends_on:
      - apache-spark-master
    volumes:
      - ../credential/projeto_data_credential.json:/opt/spark/work-dir/projeto_data_credential.json:ro
    
  apache-spark-worker-3:
    image: apache/spark:4.0.3
    container_name: apache-spark-worker-3
    restart: on-failure
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://apache-spark-master:7077
    environment:
      - SPARK_WORKER_MEMORY=3g
      - SPARK_WORKER_CORES=2
    depends_on:
      - apache-spark-master
    volumes:
      - ../credential/projeto_data_credential.json:/opt/spark/work-dir/projeto_data_credential.json:ro

  market_data_raw_producer_1:
    container_name: market_data_raw_producer_1
    build:
      context: ..
      dockerfile: docker/Dockerfile.market_data_raw_producer_1
    ports:
      - 5110:5110
    depends_on:
      - apache-spark-worker-1
      - apache-spark-worker-2
      - apache-spark-worker-3
  market_data_spark_bronze:
    container_name: market_data_spark_bronze
    build:
      context: ..
      dockerfile: docker/Dockerfile.apache_spark_bronze_ingest
    depends_on:
      - market_data_raw_producer_1
  market_data_silver:
    container_name: market_data_spark_silver
    build:
      context:  ..
      dockerfile: docker/Dockerfile.apache_spark_silver_batch
    depends_on:
      - market_data_spark_bronze

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka_market_data_plataform_cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka_broker_1:5091, kafka_broker_2:5092, kafka_broker_3:5093
    depends_on:
      - kafka_broker_1
      - kafka_broker_2
      - kafka_broker_3
