FROM apache/spark:4.0.3

WORKDIR /opt/spark/work-dir

RUN curl -o /opt/spark/jars/spark-bigquery-connector.jar \
https://storage.googleapis.com/spark-lib/bigquery/spark-4.0-bigquery-0.44.2.jar

COPY python/spark_instance.py .

CMD ["/opt/spark/bin/spark-submit", \
     "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.13:4.0.3", \
     "--conf", "spark.jars.ivy=/tmp/.ivy2", \
     "--jars", "/opt/spark/jars/spark-bigquery-connector.jar", \
     "spark_instance.py"]
